### Add product to catalog

POST https://localhost/products
Content-Type: application/x-www-form-urlencoded

name=Example product 0&price=1200

### Edit product

PUT https://localhost/products/{{product_id}}
Content-Type: application/x-www-form-urlencoded

name=New Name&price=20251

### Remove product from catalog

DELETE https://localhost/products/{{product_id}}

### List products

GET https://localhost/products

### View Product

GET https://localhost/product/{{product_id}}

### Create cart

POST https://localhost/cart

> {% client.global.set("cart_id", response.body.cart_id) %}

### Add product to cart

PUT https://localhost/cart/{{cart_id}}/{{product_id}}

quantity=2
### Remove product from cart

DELETE https://localhost/cart/{{cart_id}}/{{cart_product_id}}

### Show cart

GET https://localhost/cart/{{cart_id}}
